### ISSUE TITLE
Is it possible for a non-root user to execute?

### ISSUE THREAD

**Issue by FlyingOnion** [containerd/cgroups#89] opened 2019-06-13 13:17 UTC
It seems that the program only works when the current user is root or using sudo, but I want to launch it in the IDE directly. Anyone has ideas?

**Comment by crosbymichael** [comment] 2019-06-13 14:38
You need to be root to modify cgroups or chown a subdir of the hierarchy to modify it as non-root .

Will close this one for not as it's not a bug of this lib but feel free to ask additional questions here.

**Closed by crosbymichael** 2019-06-13 14:38 UTC

**Comment by bwplotka** [comment] 2021-08-14 20:36
Happy to share some code I used to generate programmatically the command that user has to run in order to get not-root permissions to manage cgroups using this project:

```go

const (
	mountpoint     = "/sys/fs/cgroup"
	cgroupSubGroup = "e2e"
)

(...)
		c, err := cgroups.New(cgroups.V1, cgroups.StaticPath(filepath.Join(cgroupSubGroup, "__test__")), &specs.LinuxResources{})
		if err != nil {
			if os.IsPermission(err) {
				uid := os.Getuid()

				var cmds []string

				ss, cerr := cgroups.V1()
				if cerr != nil {
					return nil, cerr
				}

				for _, s := range ss {
					cmds = append(cmds, fmt.Sprintf("sudo mkdir -p %s && sudo chown -R %d %s",
						filepath.Join(mountpoint, string(s.Name()), cgroupSubGroup),
						uid,
						filepath.Join(mountpoint, string(s.Name()), cgroupSubGroup),
					))
				}
				return nil, errors.Errorf("e2e does not have permissions, run following command: %q; err: %v", strings.Join(cmds, " && "), err)
			}
			return nil, err
		}
		if err := c.Delete(); err != nil {
			return nil, err
		}
	}

```
